### ISSUE TITLE
Idea: text/plain output for lynx/curl

### ISSUE THREAD

**Issue by ryanerwin** [sorz/moproxy#3]
It's great that I can run keep a tab open with the current `moproxy` status, but it would be even better to easily grab to optionally grab this status from the command line.

When you look at this window:
![image](https://user-images.githubusercontent.com/2156415/60806634-1b8f3280-a1b6-11e9-88cb-8fccebee92de.png)

Most of the same output would make sense in the console.
Perhaps if the User-agent is Lynx or Curl, you could just output the same chart in plain text, and if we want to keep it refreshed, we can just run `watch` it whenever we start to see problems.

**Comment by sorz** [comment]
Done. It will output plaintext if the user-agent is curl/lynx, or the Accept header is `text/plain`.
I'd say that it's a pleasure to run & watch the `watch curl -s`! Thanks.

**Comment by ryanerwin** [comment]
Awesome! This is fantastic!

```
 ❯ curl -s http://localhost:8080
 moproxy (0.2.5) is running. 14s
 ↑ 0 bps ↓ 0 bps
 +-------------------------+-------+---------+-----+-----+----+------+----+
 | Server                  | Score | Delay   | CUR | TTL | Up | Down | ↑↓ |
 | Server1-Hong-Kong       |   784 |  784 ms |   0 |   0 |    |      |    |
 | Server2-Singapore       |   938 |  938 ms |   0 |   0 |    |      |    |
 | Server3-Singapore       |  1655 | 1655 ms |   0 |   0 |    |      |    |
 | Server4-Tokyo           |     - |       - |   0 |   0 |    |      |    |
 +-------------------------+-------+---------+-----+-----+----+------+----+
```
(note I manually changed the server names in vim before posting, thus the extra spacing)

BTW, Sorry to get way off topic but I've been debating learning golang or rust... I see this is implemented in rust so I'm assuming you recommend rust. Long ago I wrote a lot of Perl and later Ruby, and a lot of shell scripts, but always wanted to learn a really fast compiled language. What are the best books or tutorials that you read about Rust?

**Comment by sorz** [comment]
[The book](https://doc.rust-lang.org/book/) and [Rust by Example](https://doc.rust-lang.org/stable/rust-by-example/)? Their official tutorials & document are pretty good.
